[package]
name = "socketcan"
version = "2.1.0-pre.0"
edition = "2021"
rust-version = "1.65"
authors = [
    "Marc Brinkmann <git@marcbrinkmann.de>",
    "Frank Pagliughi <fpagliughi@mindspring.com>"
]
documentation = "https://docs.rs/socketcan"
repository = "https://github.com/mbr/socketcan-rs"
license = "MIT"
description = """
Linux SocketCAN library. Send and receive CAN frames via CANbus on Linux.
"""

# Features:
#
# "netlink" (default) - Whether to include CAN interface configuration 
#       capabilities based on netlink kernel communications
# "dump" (default) - Whether to include 'candump' output parsing 
#	capabilities.
# "utils" - Build the command-line utilities
#

[features]
default = ["netlink", "dump"]
netlink = ["neli"]
dump = []
netlink_tests = ["netlink"]
vcan_tests = ["netlink"]
utils = ["clap", "anyhow"]

[dependencies]
embedded-can = "0.4"
nb = "1"
byte_conv = "0.1.1"
hex = "0.4"
itertools = "0.10"
libc = "0.2"
nix = "0.26"
bitflags = "1.3"
thiserror = "1.0"
clap = { version = "~4.1", optional = true }
anyhow = { version = "1.0", optional = true }
neli = { version = "0.6", optional = true }

[dev-dependencies]
anyhow = "1.0"
ctrlc = "3.2.2"
clap = { version = "~4.1", features = ["derive"] }
nb = "1.0"
serial_test = "2.0"

[[bin]]
name = "rcan"
required-features = ["utils"]
